### ISSUE TITLE
Question about myisamchk and myisampack

### ISSUE THREAD

**Issue by dportabella** [simonemainardi/load_patstat#14]
the `load_patstat.sh` script uses `myisamchk` and `myisampack`. It seems that this command requires root or mysql permision on unix. I don't have these permissions. What is the implication if I run the script without these three commands?

```
	myisamchk  --keys-used=0 -rqp $MYSQLDATAPATH/$DB/$1*.MYI
        ...
	myisampack $MYSQLDATAPATH/$DB/$1.MYI
        ...
	myisamchk  -rqp --sort-buffer-size=2G $MYSQLDATAPATH/$DB/$1*.MYI
```

**Comment by simonemainardi** [comment]
`myisamck` and `myisampack` require write access to the mysql data dir. You can drop sudo provided that your user has such write privileges on the mysql data directory.

**Comment by dportabella** [comment]
that's the thing; my user does not have such privileges, and the database administrator will not give them to me. The question is what happens if I do not run these three commands? it will take longer time to import the database? that's all? or there will be some other problem?

**Comment by simonemainardi** [comment]
Yes, removing the myisamck that disables indices updates during import will yield a tremendous increase in the import time.

Similarly, removing the myisampack will yield larger tables on disk and slower fetch times.

If you can't get write access to the mysql datadir, you can spawn a new mysql process in a data dir that is writable to you, do the import process there, and finally give the created .frm, .MYD and .MYI files to your DBA that can put them in the original mysql data dir. Note that you can only copy database files because they are MyISAM. Don't even try to do that if you changed the engine to InnoDB as you will end un in a corrupted db.

**Comment by dportabella** [comment]
the script took 15 hours to import the data without these three commands. That's ok for us.
the "larger tables" issue is not important to us neither.
but the slower fetch times is indeed an argument for us.
thx!
